In [4]:
# prin()함수도 역시 *args를 받는 형식이다. ','를 구분으로 받아서 인자를 계속 출력하기 때문.
# dict()역시 가변키워드인수를 받아서 처리하는 형식이다.

In [7]:
a={
    'name':'tom',
    'email':'asdf@asdf.com'
}

In [5]:
b=dict(
name = 'tom',
email = 'asdf@asdf.com')

In [8]:
a

{'name': 'tom', 'email': 'asdf@asdf.com'}

In [9]:
b

{'name': 'tom', 'email': 'asdf@asdf.com'}

In [39]:
class Dog:
    def __init__(self,name,color): #속성 #init은 생성자, self는 자신, name,color는 인자
        self.hungry = 0
        self.name = name
        self.color = color
        
    def eat(self): # 메소드
        self.hungry -= 10
        print('밥먹음', self.hungry)
        
    def walk(self):
        self.hungry += 10
        print('산책', self.hungry)

In [40]:
my_dog = Dog('choco', 'chocolate')

In [41]:
my_dog.walk()

산책 10


In [20]:
my_dog.eat()

밥먹음 0


In [42]:
my_dog.hungry

10

In [61]:
class Dog:
    class_dog_total = 0
    
    @staticmethod
    def get_eye_num(): #여기엔 아무것도 넣지않는다.
        return 2
    
    
    @classmethod
    def make_new_dog(cls):
        print(cls)

        pass
    
    @classmethod
    def make_new_yok(cls):
        cls.class_dog_total+=1
        return cls('yok', 'brown')
    
    #클래스메소드가 아닌 아래 메소드들은 인스턴스들을 위한 메소드들이다.
    def __init__(self,name,color): #속성 #init은 생성자, self는 자신, name,color는 인자
        self.hungry = 0
        self.name = name
        self.fur_color = color
        
    def eat(self): # 메소드
        self.hungry -= 10
        print('밥먹음', self.hungry)
        
    def walk(self):
        self.hungry += 10
        print('산책', self.hungry)

In [68]:
Dog.make_new_dog()
print(Dog)

<class '__main__.Dog'>
<class '__main__.Dog'>


In [62]:
Dog.make_new_yok()

In [63]:
Dog.class_dog_total

1

In [64]:
Dog.get_eye_num()

2

In [65]:
yoki=Dog.make_new_yok()
yoki.walk()
yoki.hungry

산책 10


10

# 연습문제1

In [356]:
class Car(object):
    total_num = 0
    
    @classmethod
    def total(cls):
        print(cls.total_num)
    
    def __init__(self, name, emit, madeyear):
        self.__name = name
        self.__emit = emit
        self.__madeyear = madeyear
        Car.total_num += 1 #cls가아닌 Car에 주의
        
    def namechange(self,hopename):
        self.__name = hopename
        
    def size(self):
        if self.__emit <= 1000:
            print('소형')
        elif self.__emit <= 2000:
            print('중형')
        else:
            print('대형')
            
    def get_name(self):
        return self.__name
    def get_emit(self):
        return self.__emit
    def get_madeyear(self):
        return self.__madeyear

In [357]:
car1 = Car('a',900,'19950202')
car2 = Car('b',1500,'19950203')
car3 = Car('c',2100,'19950204')
car4 = Car('d',2200,'19950205')

In [358]:
name_list = ['d','e','f','g']
emit_list = [501, 1001, 1501, 2001]
madeyear_list = ['19950205','19950206','19950207','19950208']

total_list = list(zip(name_list, emit_list, madeyear_list))
print(total_list)

[('d', 501, '19950205'), ('e', 1001, '19950206'), ('f', 1501, '19950207'), ('g', 2001, '19950208')]


In [380]:


for idx, val in enumerate(total_list):
    code = "car{} = Car('{}', {}, '{}')".format(idx, val[0], val[1], val[2]) #""안에 ''로 감싸진 것에 주의
    exec(code) # exec는 eval의 하위함수


In [381]:
car1.get_name()

'e'

In [382]:
car2.get_name()

'f'

In [371]:
exec("ca2 = Car('a',900,'19950202')")

In [372]:
ca2

In [214]:
car1.get_name()

'a'

In [215]:
car1.namechange('asdf')
car1.get_name()

'asdf'

In [216]:
car1.size()
car2.size()
car3.size()

소형
중형
대형


In [217]:
Car.total_num

3

In [218]:
Car.total()

3


In [219]:
class Car(object):
    
    @classmethod
    def temp_cm(cls):
        pass
    
    @classmethod
    def make_bmw(cls):
        return cls('bmw')
    
    @staticmethod            #강박증이 만들어낸 스태틱메소드
    def temp_sm():
        pass
    
    #method
    def temp_method(self):
        pass
    
    pass


In [220]:
my_car = Car()

# 연식따라나누기

In [223]:
my_car = Car("BMW", 3000, '2019')
my_car.get_madeyear()

'2019'

In [224]:
my_dict= {}
year = my_car.get_madeyear()

In [225]:
if year not in my_dict:
    my_dict[year] = []

In [226]:
my_dict[year].append(my_car)

In [227]:
#위의 과정을 한 함수에 저장해서 사용하는게 첫번째 방법

In [271]:
class Car(object):
    total_num = 0
    year_dict ={}
    
    @classmethod
    def total(cls):
        print(cls.total_num)
    
    def __init__(self, name, emit, year):
        self.__name = name
        self.__emit = emit
        self.__year = year
        Car.total_num += 1 #cls가아닌 Car에 주의
        
        #연식딕트만들기
        if self.__year not in Car.year_dict:
            Car.year_dict[self.__year] = []
        Car.year_dict[self.__year].append(self)    #append()안에 self만 넣어도 돌아간다!!
        
    @classmethod
    def get_cars_by_year(cls,year):
        #cls = Car
        year_dict = cls.year_dict
        if year not in year_dict:
            return []
        else:
            return year_dict[year]
        
#     #매직메소드, 어떤 형식으로 볼지결정, 이거 안됨
#     def __str__(self):
#         return self.__name + self.__emit + self.__year
    #매직메소드, 어떻게 볼지결정
    def __repr__(self):
        return "[{},{},{}]".format(self.__name , self.__emit , self.__year)
        
        
    def namechange(self,hopename):
        self.__name = hopename
        
    def size(self):
        if self.__emit <= 1000:
            print('소형')
        elif self.__emit <= 2000:
            print('중형')
        else:
            print('대형')
            
    def get_name(self):
        return self.__name
    def get_emit(self):
        return self.__emit
    def get_year(self):
        return self.__year

In [272]:
car1 = Car('a',900,'1995')
car2 = Car('b',1500,'1995')
car3 = Car('c',2100,'1996')
car4 = Car('d',2200,'1997')

In [273]:
(Car.year_dict)

{'1995': [[a,900,1995], [b,1500,1995]],
 '1996': [[c,2100,1996]],
 '1997': [[d,2200,1997]]}

In [276]:
car_1995 = Car.get_cars_by_year('1995')
Car.get_cars_by_year('1995')

[[a,900,1995], [b,1500,1995]]

In [283]:
for car in car_1995:
    size = car.size() # 반복해서 클래스를 넣고 출력.
    
print(size)

소형
중형
None


In [280]:
print(type(car_1995))
print(type(car_1995[0]))

<class 'list'>
<class '__main__.Car'>


# 예외처리

In [288]:
try:                      # 일단시도
    print(10/0)
except:                   # 에러가 나면 실행
    print("예외오류발생")
#트라이익셉문

예외오류발생


In [302]:
x=[1,2,3]

try:
    print(10/0)
    x[5]
    
except ZeroDivisionError as e:
    print('숫자를 0으로 나눌 수 없음', e) # 뒤의 e는 에러임. 에러출력함.
except IndexError as e:
    print('잘못된 인덱스', e)
else:
    print('except문이 실행이 안되면 실행됩니다.')
    
finally:
    print('finally가 실행되었습니다.')

숫자를 0으로 나눌 수 없음 division by zero
finally가 실행되었습니다.


In [303]:
x=[1,2,3]

try:
    a=1
    print(a)
    
except ZeroDivisionError as e:
    print('숫자를 0으로 나눌 수 없음', e) # 뒤의 e는 에러임. 에러출력함.
except IndexError as e:
    print('잘못된 인덱스', e)
else:
    print('except문이 실행이 안되면 실행됩니다.')
    
finally:
    print('finally가 실행되었습니다.')

1
except문이 실행이 안되면 실행됩니다.
finally가 실행되었습니다.


## 일부러 에러 발생시키기

In [305]:
raise Exception('message')
# Exception도 클래스다.
# IndexError는 Exception의 상속클래스
# 그러므로 예외를 만들어서 사용할 수도 있다.

Exception: message

In [306]:
try:
    raise Exception('message')
except:
    print('에러가 처리되었습니다.')

에러가 처리되었습니다.


In [307]:
class MyException(Exception): #에러를 정의해놓기
    pass

In [309]:
try:
    raise MyException('내 에러다.')
except MyException as e:
    print('my exception입니다.블라블라')
    print(e)

my exception입니다.블라블라
내 에러다.


In [310]:
dir(Exception)

['__cause__',
 '__class__',
 '__context__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__suppress_context__',
 '__traceback__',
 'args',
 'with_traceback']

In [1]:
Exception.with_traceback

<method 'with_traceback' of 'BaseException' objects>

#  모듈

In [315]:
# .py가 파이썬 파일
# .ipynb가 주피터파이썬 파일
import sys
sys.path

['C:\\Users\\Funzo\\python gicho',
 'C:\\Users\\Funzo\\Anaconda3\\python37.zip',
 'C:\\Users\\Funzo\\Anaconda3\\DLLs',
 'C:\\Users\\Funzo\\Anaconda3\\lib',
 'C:\\Users\\Funzo\\Anaconda3',
 '',
 'C:\\Users\\Funzo\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\Funzo\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Funzo\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Funzo\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Funzo\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Funzo\\.ipython']

In [325]:
%%writefile calc2.py
#주피터에서 파일을 빼는건 한 셀 단위로 가능하다.

def calc_sum(a,b):
    return a+b

def calc_mul(a,b):
    return a*b

def calc_sub(a,b):
    return a-b

Writing calc2.py


In [327]:
import calc2
calc2.calc_sum(1,5)

6

In [328]:
from calc2 import calc_sum
calc_sum(5,5)

10

In [ ]:
#모듈은 파이썬파일이 여러개, 패키지는 모듈이 여러개.

# 연습문제!! - 개미문제

In [429]:
l1=[1,1,2,3,1,2,3,1,1,1]

In [574]:
def rep_n(lst):
    n = 0
    for i in range(len(lst)):
        if lst[0] == lst[i]:
            n += 1
        else:
            break
    return(n)

In [575]:
rep_n([1,2,3])

1

In [595]:
def getFgetR(lst):
    temp = []
    a=lst[0]
    b=rep_n(lst)
    temp.extend([a,b])
    
    del lst[:int(b)]
    return temp, lst

In [596]:
l1 = [1,1,2,3]
result = getFgetR(l1)
print(result)
print(l1)

([1, 2], [2, 3])
[2, 3]


In [618]:
def next_list(lst):
    nxt = []
    for i in range(len(lst)):
#         print(getFgetR(lst)[0])
        
        nxt.extend(getFgetR(lst)[0])
#         lst = getFgetR(lst)[1]
        if len(lst)==0:
            break
    return nxt

In [619]:
l1 = [1,1,2,3]
result = next_list(l1)
# print(result)
# print(l1)

In [620]:
l1=[1]
input_number = int(input('몇번째 개미수열을 보겠습니까 : '))
for i in range(input_number-1):
    l1=next_list(l1)

print(l1)

[1, 1, 2, 2, 1, 3]


# 개미수열 정답코드

In [6]:
def rep_n(lst):
    n = 0
    for i in range(len(lst)):
        if lst[0] == lst[i]:
            n += 1
        else:
            break
    return(n)

def getFgetR(lst):
    temp = []
    a=lst[0]
    b=rep_n(lst)
    temp.extend([a,b])
    
    del lst[:int(b)]
    return temp, lst

def next_list(lst):
    nxt = []
    for i in range(len(lst)):
        nxt.extend(getFgetR(lst)[0])  # lst = getFgetR(lst)[1] 추가하면 lst를 또 줄이는 쓸데없는 짓
        if len(lst)==0:
            break
    return nxt

l1=[1]
input_number = int(input('몇번째 개미수열을 보겠습니까 : '))
for i in range(input_number-1):
    l1=next_list(l1)

print(l1)

몇번째 개미수열을 보겠습니까 : 15
[1, 2, 2, 2, 1, 2, 3, 1, 1, 2, 2, 3, 1, 1, 3, 2, 1, 2, 2, 2, 3, 1, 1, 1, 2, 1, 3, 1, 1, 2, 2, 1, 3, 1, 1, 1, 2, 1, 1, 2, 2, 3, 1, 2, 3, 1, 1, 3, 2, 1, 1, 2, 3, 1, 2, 1, 1, 1, 3, 1, 1, 3, 2, 1, 1, 1, 3, 1, 1, 2, 2, 2, 1, 1, 3, 1, 1, 3]


# 피보나치

In [2]:
n=int(input('피보나치 수열의 몇번째를 보시겠습니까? '))
init_lst = [1,1]
for i in range(n-2):
    init_lst.append(init_lst[-1]+init_lst[-2])
init_lst[n-1]

피보나치 수열의 몇번째를 보시겠습니까? 100


354224848179261915075

# 세번째 ppt 시작

## numpy

In [465]:
import numpy as np
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [466]:
type(a)

numpy.ndarray

In [467]:
l1 = [5,4,8,10]
b = np.array(l1)
b

array([ 5,  4,  8, 10])

In [468]:
a.dtype

dtype('int32')

In [469]:
b.dtype

dtype('int32')

In [470]:
l2 = [1,2.0,3, 'a']
l2

[1, 2.0, 3, 'a']

In [471]:
np.array(l2)

array(['1', '2.0', '3', 'a'], dtype='<U32')

In [474]:
l3 = [1,2.0,3,5.9]
c = np.array(l3)
c

array([1. , 2. , 3. , 5.9])

In [475]:
c.dtype

dtype('float64')

In [476]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [477]:
b

array([ 5,  4,  8, 10])

In [478]:
c

array([1. , 2. , 3. , 5.9])

In [479]:
a.shape

(10,)

In [480]:
print(b.shape)
print(c.shape)

(4,)
(4,)


## 차원의 개념

In [481]:
l1 = [[1,2],[3,4]]
a=np.array(l1)
a

array([[1, 2],
       [3, 4]])

In [482]:
a.dtype

dtype('int32')

In [483]:
a.shape

(2, 2)

In [486]:
l2 = [[1,2,3], [3,4]]
b = np.array(l2)
b
# 길이가 같아야 2차원 만듬

array([list([1, 2, 3]), list([3, 4])], dtype=object)

In [487]:
b.shape

(2,)

In [489]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [490]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [491]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [493]:
np.linspace(10,20,9)

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

In [498]:
np.linspace(10,59)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49., 50., 51., 52., 53., 54., 55., 56., 57., 58., 59.])

## shape

In [499]:
a = np.arange(2,10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [500]:
a.shape

(8,)

In [501]:
b = a.reshape(2,4)

In [502]:
b

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [503]:
b.shape

(2, 4)

## 또 다른 방법

In [504]:
a.shape = (2,4) # shape는 numpy의 속성임.

In [505]:
a

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [506]:
a.shape = -1 # 요소의 갯수를 알땐 a.shape = (8,)와 같다.
a

array([2, 3, 4, 5, 6, 7, 8, 9])

## astype

In [511]:
a=np.linspace(0,100)

In [512]:
a.dtype

dtype('float64')

In [513]:
b=a.astype(str)
b

array(['0.0', '2.0408163265306123', '4.081632653061225',
       '6.122448979591837', '8.16326530612245', '10.204081632653061',
       '12.244897959183675', '14.285714285714286', '16.3265306122449',
       '18.367346938775512', '20.408163265306122', '22.448979591836736',
       '24.48979591836735', '26.53061224489796', '28.571428571428573',
       '30.612244897959183', '32.6530612244898', '34.69387755102041',
       '36.734693877551024', '38.775510204081634', '40.816326530612244',
       '42.85714285714286', '44.89795918367347', '46.93877551020408',
       '48.9795918367347', '51.02040816326531', '53.06122448979592',
       '55.10204081632653', '57.142857142857146', '59.183673469387756',
       '61.224489795918366', '63.26530612244898', '65.3061224489796',
       '67.34693877551021', '69.38775510204081', '71.42857142857143',
       '73.46938775510205', '75.51020408163265', '77.55102040816327',
       '79.59183673469389', '81.63265306122449', '83.6734693877551',
       '85.71428571428572

In [514]:
c = a.astype(int)
c

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [516]:
np.random.rand(2,3)

array([[0.61959379, 0.53963319, 0.0585974 ],
       [0.25986441, 0.03149502, 0.31046991]])

In [517]:
np.random.randint(1,10, 28).reshape(4,7)

array([[6, 7, 5, 5, 5, 3, 6],
       [4, 8, 2, 3, 3, 6, 5],
       [2, 3, 9, 7, 9, 6, 7],
       [3, 3, 7, 3, 6, 7, 7]])

In [522]:
np.random.randn(3,2) # 평균0 표준편차1

array([[-0.08623783,  0.06836944],
       [-0.85157392,  0.08623664],
       [ 0.47529745,  1.15921704]])

## 인덱스

In [527]:
a=np.linspace(1,20,9)
a

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [528]:
print(a[1])

3.375


### 배열부분인덱싱

In [1]:
import numpy as np
arr1 = np.arange(0,60,10)

In [2]:
arr1[[1,4]] # [[]]안에 쓴다. 갖고오고싶은 인덱스 여러개 가져온다.

array([10, 40])

In [11]:
arr1 = np.arange(10,20)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
arr1[[0,7]]

array([10, 17])

In [15]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
arr1[0, 0]

0

In [22]:
arr1[[0,2]]

array([[0, 1, 2],
       [6, 7, 8]])

In [23]:
arr1[[0,2],]

array([[0, 1, 2],
       [6, 7, 8]])

In [24]:
arr1[[0,2],[1,2]]

array([1, 8])

In [29]:
arr1[[0,2],[0,2]]

array([0, 8])

In [529]:
a = a.reshape(3,3)
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [530]:
a[1][2] # 이것보다 아래것이 더 연산이 더 빠르다. [1]할때 그 행을 만들기때문.

12.875

In [531]:
a[1,2] # [[1,2]]는 부분인덱싱이다. 헷갈리지 말자. # 여기에 값을 지정하면 (a[1,2]=13) 값도 수정가능

12.875

In [532]:
a[1:]

array([[ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [533]:
a[:2]

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875]])

In [534]:
a[:,:2] #다 갖고오는데, 열만 2 이하로

array([[ 1.   ,  3.375],
       [ 8.125, 10.5  ],
       [15.25 , 17.625]])

In [535]:
a[:,1:]

array([[ 3.375,  5.75 ],
       [10.5  , 12.875],
       [17.625, 20.   ]])

In [536]:
b=a.reshape(-1)
b

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [537]:
b[1::2] #1칸씩 건너뛰어서 가져온다

array([ 3.375,  8.125, 12.875, 17.625])

In [538]:
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [539]:
a[::2,::2] #행 쪽으로 1칸씩 뛰어서, 열 방향으로도 1칸씩 뛰어서

array([[ 1.  ,  5.75],
       [15.25, 20.  ]])

In [540]:
b

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [542]:
b[b>10] #이렇게 조건으로 인덱싱하면 행렬을 전부 벡터로 변환한다.

array([10.5  , 12.875, 15.25 , 17.625, 20.   ])

In [551]:
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [552]:
a[1, a[1]>9]  #1행중 9보다 큰 값

array([10.5  , 12.875])

In [3]:
arr2 = np.arange(10, 170, 10).reshape(4, 4)
arr2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [4]:
arr2[:-1:2, ::2] #처음부터 -1행까지 범위지정, 한 칸씩 건너뛰며 가져온다.

array([[ 10,  30],
       [ 90, 110]])

In [553]:
np.nan

nan

In [5]:
np.inf

inf

In [8]:
a=np.array([np.inf])
a.dtype

dtype('float64')

In [9]:
a=np.array([np.nan])
a.dtype

dtype('float64')

## 연산

In [556]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [558]:
a+1 #드디어 벡터연산!

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [559]:
np.arange(10) + np.arange(50,60)

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68])